language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

script:
  - sbt 'test-only sss.finals.F* sss.finals.I* sss.finals.N*'

notifications:
  webhooks:
    urls: 
      - https://webhooks.gitter.im/e/a4f6323d288ed6c5d2b1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
